version: '3'

services:
  letsencrypt:
    restart: unless-stopped
    image: linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      PGID: 1000
      PUID: 1000
      EMAIL: sysadmin@vtluug.org
      # URL field must be working since nginx only starts if letsencrypt works
      URL: vtluug.org
      SUBDOMAINS: www,bash,id,irc,sczi,wiki,element,search,matrix,git,bitwarden,soulseek,social,seed,openwebui
      EXTRA_DOMAINS: gobblerpedia.org,www.gobblerpedia.org,hokieprivacy.org,www.hokieprivacy.org,distributions.pconte.me
      VALIDATION: html # TODO Switch to dns + gandi api once pr is merged
      TZ: America/New_York
    volumes:
      # nginx config
      - /nfs/cistern/docker/data/nginx/config:/config
      - ./nginx.conf:/config/nginx/nginx.conf:ro
      - ./ssl.conf:/config/nginx/ssl.conf:ro
      - ./site-confs:/config/nginx/site-confs:ro
      - ./jail.local:/config/jail2ban/jail.local:ro
      # general static stuff
      - /nfs/cistern/files:/files:ro
      - /nfs/cistern/home:/users:ro
      # hokieprivacy static site
      - /nfs/cistern/docker/data/hokieprivacy:/hokieprivacy:ro
      # wiki images
      - /nfs/cistern/docker/data/wiki/images:/wiki-images:ro
    ports:
      - 128.173.88.78:80:80
      - 128.173.88.78:443:443
      - 128.173.88.78:8448:8448 # matrix federation
      - 2607:b400:0006:cc80:0000:0aff:fe62:000b:80:80
      - 2607:b400:0006:cc80:0000:0aff:fe62:000b:443:443
      - 2607:b400:0006:cc80:0000:0aff:fe62:000b:8448:8448 # matrix federation

networks:
  default:
    external:
      name: vtluug-network
